name: Publish Package to npmjs

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-24.04

    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4

      - name: ASDF Setup
        uses: asdf-vm/actions/setup@v3

      - name: Restore ASDF tools from cache
        id: asdf-tools-cache
        uses: actions/cache@v4
        with:
          key: asdf-tools-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            asdf-tools-
          path: |
            ${{ env.ASDF_DIR }}/plugins
            ${{ env.ASDF_DIR }}/installs

      - name: Install ASDF tools on cache-miss
        if: ${{ steps.asdf-tools-cache.outputs.cache-hit != 'true' }}
        uses: asdf-vm/actions/install@v3
        
      - name: Reshim installed ASDF tools
        shell: bash
        run: asdf reshim

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Deploy
        run: npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}